export const LOAD = 'summaries/LOAD'
export const FETCH_REQUEST = 'summaries/FETCH_REQUEST'
export const FETCH_SUCCESS = 'summaries/FETCH_SUCCESS'
export const FETCH_FAILURE = 'summaries/FETCH_FAILURE'
export const CLEAR = 'summaries/CLEAR'
