export const FETCH_TRIGGER = 'comments/FETCH_TRIGGER'
export const FETCH_REQUEST = 'comments/FETCH_REQUEST'
export const FETCH_SUCCESS = 'comments/FETCH_SUCCESS'
export const FETCH_FAILURE = 'comments/FETCH_FAILURE'
export const CLEAR = 'comments/CLEAR'

export const FETCH_REPLIES_TRIGGER = 'comments/FETCH_REPLIES_TRIGGER'
export const FETCH_REPLIES_REQUEST = 'comments/FETCH_REPLIES_REQUEST'
export const FETCH_REPLIES_SUCCESS = 'comments/FETCH_REPLIES_SUCCESS'
export const FETCH_REPLIES_FAILURE = 'comments/FETCH_REPLIES_FAILURE'
