import MarkdownEngine from '../../utils/MarkdownEngine'

export const story = {
  id: 'z810j',
  created: 1513920502005,
  edited: null,
  title: 'No siempre son los Simpson',
  nsfw: false,
  classic: {
    tid: 'cECmd',
    type: 'shout',
  },
  tags: ['image', 'classic'],
  slug: 'barbarapalvin-es-perfecta-mira-esos-ojos_z810j',
  type: 'story',
  active: true,
  content: MarkdownEngine.Render([
    {
      type: 'markdown',
      body: '<hashtag tag="BarbaraPalvin" /> Es perfecta, mira esos ojos 💙',
    },
    {
      type: 'image',
      caption: '',
      url: 'https://k60.kn3.net/taringa/2/2/1/1/0/4/46/outlookmi/8E2.jpg',
      width: 517,
      height: 800,
      format: 'jpeg',
    },
  ]),
  channel: {
    type: 'channel:summary',
    id: '2fz',
    created: '2016-08-05T18:53:28.000Z',
    name: 'user-Outlookmi',
    title: 'user-Outlookmi',
    channelType: 'user_feed',
    thumbnail: '',
    background: '',
    description: '',
    category: 'unknown/unknown',
    owner: {
      id: '2em',
      created: '2016-08-05T18:53:27.000Z',
      type: 'user',
      tid: 22110446,
      username: 'Outlookmi',
      firstname: 'Eylice',
      lastname: 'Serés ✪',
      birthday: '1996-6-11',
      avatar:
        'https://a20.t26.net/taringa/avatares/1/E/3/4/3/9/Outlookmi/120x120_CCD.jpg',
      site: 'http://www.taringa.com/Outlookmi',
      gender: 'm',
      country: 'AR',
      message:
        '● Subo buenas imágenes y gifs de todo tipo ● #PorElMundo - Los mejores lugares en fotografías alrededor del planeta ● Sígueme y te sigo【✔】●',
      migrated: [],
      subscribedToDefaultChannels: false,
      rank: 'User',
    },
    subscribers: 0,
    stories: 5797,
    latestStory: '2018-01-30T02:45:10.000Z',
    state: {
      subscription: 'unsubscribed',
    },
  },
  owner: {
    id: '2em',
    username: 'Outlookmi',
    type: 'user:summary',
    firstname: 'Eylice',
    lastname: 'Serés ✪',
    avatar:
      'https://a20.t26.net/taringa/avatares/1/E/3/4/3/9/Outlookmi/120x120_CCD.jpg',
    gender: 'm',
    country: 'AR',
  },
  upvotes: 47,
  downvotes: 0,
  shares: 0,
  comments: 2,
  brandSafe: false,
  listViewSafe: false,
  state: {},
}
