export const SEARCH_TRIGGER = 'search/SEARCH_TRIGGER'
export const SEARCH_REQUEST = 'search/SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'search/SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'search/SEARCH_FAILURE'
export const SEARCH_CLEAR = 'search/SEARCH_CLEAR'
export const SEARCH_CANCEL = 'search/SEARCH_CANCEL'
