export const SEARCH_TRIGGER = 'search/SEARCH_TRIGGER'

export const SEARCH_START = 'search/SEARCH_START'
export const SEARCH_FINISH = 'search/SEARCH_FINISH'

export const SEARCH_USERS_REQUEST = 'search/SEARCH_USERS_REQUEST'
export const SEARCH_USERS_SUCCESS = 'search/SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAILURE = 'search/SEARCH_USERS_FAILURE'

export const SEARCH_STORIES_REQUEST = 'search/SEARCH_STORIES_REQUEST'
export const SEARCH_STORIES_SUCCESS = 'search/SEARCH_STORIES_SUCCESS'
export const SEARCH_STORIES_FAILURE = 'search/SEARCH_STORIES_FAILURE'

export const SEARCH_CLEAR = 'search/SEARCH_CLEAR'
